spring:
  profiles:
    active: local

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true

    # fieild name accept using camel case
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

---
spring:
  profiles: local

  datasource:
    username: root
    password: 1234
    url: jdbc:mariadb://localhost:3307/profiler?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowMultiQueries=true
    initialization-mode: always
  #    data: classpath:data.sql

  jpa:
    hibernate:
      ddl-auto: create

---
spring:
  profiles: test

  datasource:
    username: ptech
    password: ptech6441
    url: jdbc:mariadb://13.125.199.14:3306/author?characterEncoding=UTF-8&amp;serverTimezone=Asia/Seoul

#  jpa:
#    hibernate:
#      ddl-auto: create-drop
