# https://javachoi.tistory.com/413
version: "3.7"

services:

  zookeeper1:
    image: zookeeper
    hostname: zookeeper1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    volumes:
      - ./config/zookeeper/zookeeper1/data:/data
      - ./config/zookeeper/zookeeper1/datalog:/datalog
    restart: unless-stopped

  zookeeper2:
    image: zookeeper
    hostname: zookeeper2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    volumes:
      - ./config/zookeeper/zookeeper2/data:/data
      - ./config/zookeeper/zookeeper2/datalog:/datalog
    restart: unless-stopped

  zookeeper3:
    image: zookeeper
    hostname: zookeeper3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    volumes:
      - ./config/zookeeper/zookeeper3/data:/data
      - ./config/zookeeper/zookeeper3/datalog:/datalog
    restart: unless-stopped

  kafka1:
    image: confluentinc/cp-kafka
    user: "0"
    ports:
      - 9091:9091
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://164.125.37.214:9091
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9091
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      - KAFKA_BROKER_ID=1
      - BOOTSTRAP_SERVERS=kafka1:9091,kafka2:9092,kafka3:9093
    volumes:
      - ./config/kafka/kafka1/data:/var/lib/kafka/data
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    restart: unless-stopped

  kafka2:
    image: confluentinc/cp-kafka
    user: "0"
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://164.125.37.214:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      - KAFKA_BROKER_ID=2
      - BOOTSTRAP_SERVERS=kafka1:9091,kafka2:9092,kafka3:9093
    volumes:
      - ./config/kafka/kafka2/data:/var/lib/kafka/data
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    restart: unless-stopped

  kafka3:
    image: confluentinc/cp-kafka
    user: "0"
    ports:
      - 9093:9093
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://164.125.37.214:9093
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9093
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      - KAFKA_BROKER_ID=3
      - BOOTSTRAP_SERVERS=kafka1:9091,kafka2:9092,kafka3:9093
    volumes:
      - ./config/kafka/kafka3/data:/var/lib/kafka/data
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    restart: unless-stopped

#  zoo-navi:
#    image: elkozmon/zoonavigator
#    ports:
#      - 9000:9000
#    environment:
#      HTTP_PORT: 9000
#    restart: unless-stopped

  kafka-manager:
    image: hlebalbau/kafka-manager:stable
    ports:
      - 9000:9000
    environment:
      ZK_HOSTS: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      APPLICATION_SECRET: random-secret
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    restart: unless-stopped
